-- =====================================================================
-- Consensus Radar — scale catalogue
--
-- GENERATED FILE. Do not edit by hand: change src/lib/scales-data.ts and run
--   npm run scales:sql
--
-- 262 pairs (180 general, 82 analytics).
--
-- Run this in the Supabase SQL Editor after supabase/schema.sql. Safe to
-- re-run: rows are matched on `key`.
--
-- Note that re-running RESETS labels to the values in this file. If you edit a
-- pair from the dashboard and want to keep it, put the change in
-- src/lib/scales-data.ts too. Adding your own pairs from the dashboard is
-- safe — this file never deletes anything.
--
-- To retire a pair without losing its history, set enabled = false:
--   update public.scales set enabled = false where key = 'some_key';
-- =====================================================================

insert into public.scales (key, category, left_ua, right_ua, left_en, right_en) values
  ('risky_safe', 'general', 'Ризиковано', 'Безпечно', 'Risky', 'Safe'),
  ('hot_cold', 'general', 'Гаряче', 'Холодне', 'Hot', 'Cold'),
  ('hard_easy', 'general', 'Складно', 'Легко', 'Hard', 'Easy'),
  ('useful_useless', 'general', 'Корисно', 'Марно', 'Useful', 'Useless'),
  ('funny_cringe', 'general', 'Смішно', 'Крінжово', 'Funny', 'Cringe'),
  ('genius_nonsense', 'general', 'Геніально', 'Повна дурня', 'Genius', 'Total nonsense'),
  ('urgent_canwait', 'general', 'Терміново', 'Може почекати', 'Urgent', 'Can wait'),
  ('expensive_cheap', 'general', 'Дуже дорого', 'Дуже дешево', 'Very expensive', 'Very cheap'),
  ('over_underrated', 'general', 'Переоцінено', 'Недооцінено', 'Overrated', 'Underrated'),
  ('normal_weird', 'general', 'Звичайне', 'Дивне', 'Normal', 'Weird'),
  ('intro_extrovert', 'general', 'Інтроверт', 'Екстраверт', 'Introvert', 'Extrovert'),
  ('movie_under_hyped', 'general', 'Недооцінений фільм', 'Хайповий фільм', 'Underrated movie', 'Hyped movie'),
  ('good_evil', 'general', 'Добро', 'Зло', 'Good', 'Evil'),
  ('loud_quiet', 'general', 'Гучно', 'Тихо', 'Loud', 'Quiet'),
  ('big_small', 'general', 'Велике', 'Маленьке', 'Big', 'Small'),
  ('fast_slow', 'general', 'Швидко', 'Повільно', 'Fast', 'Slow'),
  ('old_new', 'general', 'Старе', 'Нове', 'Old', 'New'),
  ('clean_dirty', 'general', 'Чисте', 'Брудне', 'Clean', 'Dirty'),
  ('soft_solid', 'general', 'М''яке', 'Тверде', 'Soft', 'Hard'),
  ('bright_dark', 'general', 'Світле', 'Темне', 'Bright', 'Dark'),
  ('wet_dry', 'general', 'Мокре', 'Сухе', 'Wet', 'Dry'),
  ('heavy_light', 'general', 'Важке', 'Легке', 'Heavy', 'Light'),
  ('round_sharp', 'general', 'Кругле', 'Гостре', 'Round', 'Sharp'),
  ('smooth_rough', 'general', 'Гладке', 'Шорстке', 'Smooth', 'Rough'),
  ('simple_complex', 'general', 'Просте', 'Складне', 'Simple', 'Complex'),
  ('beautiful_ugly', 'general', 'Красиве', 'Потворне', 'Beautiful', 'Ugly'),
  ('cute_scary', 'general', 'Миле', 'Страшне', 'Cute', 'Scary'),
  ('serious_silly', 'general', 'Серйозно', 'Несерйозно', 'Serious', 'Silly'),
  ('formal_casual', 'general', 'Формально', 'Неформально', 'Formal', 'Casual'),
  ('polite_rude', 'general', 'Ввічливо', 'Грубо', 'Polite', 'Rude'),
  ('brave_cowardly', 'general', 'Смілово', 'Боязко', 'Brave', 'Cowardly'),
  ('lucky_unlucky', 'general', 'Щасливчик', 'Невдаха', 'Lucky', 'Unlucky'),
  ('boring_exciting', 'general', 'Нудно', 'Захопливо', 'Boring', 'Exciting'),
  ('calm_chaotic', 'general', 'Спокійно', 'Хаотично', 'Calm', 'Chaotic'),
  ('relaxing_stressful', 'general', 'Розслабляє', 'Стресує', 'Relaxing', 'Stressful'),
  ('comfy_uncomfy', 'general', 'Комфортно', 'Незручно', 'Comfy', 'Uncomfortable'),
  ('cozy_sterile', 'general', 'Затишно', 'Стерильно', 'Cosy', 'Sterile'),
  ('friendly_intimidating', 'general', 'Дружньо', 'Лякає', 'Friendly', 'Intimidating'),
  ('wholesome_dark', 'general', 'Мило й тепло', 'Темно', 'Wholesome', 'Dark'),
  ('tidy_messy', 'general', 'Порядок', 'Хаос', 'Tidy', 'Messy'),
  ('sweet_salty', 'general', 'Солодке', 'Солоне', 'Sweet', 'Salty'),
  ('bitter_sweet', 'general', 'Гірке', 'Солодке', 'Bitter', 'Sweet'),
  ('spicy_bland', 'general', 'Гостре', 'Пресне', 'Spicy', 'Bland'),
  ('crunchy_soggy', 'general', 'Хрустке', 'Розмокле', 'Crunchy', 'Soggy'),
  ('healthy_junk', 'general', 'Здорова їжа', 'Фастфуд', 'Healthy food', 'Junk food'),
  ('breakfast_dinner', 'general', 'Сніданок', 'Вечеря', 'Breakfast food', 'Dinner food'),
  ('snack_meal', 'general', 'Перекус', 'Повноцінний обід', 'A snack', 'A full meal'),
  ('drink_dessert', 'general', 'Напій', 'Десерт', 'A drink', 'A dessert'),
  ('sandwich_not', 'general', 'Це сендвіч', 'Це не сендвіч', 'That''s a sandwich', 'That''s not a sandwich'),
  ('soup_not', 'general', 'Це суп', 'Це не суп', 'That''s a soup', 'That''s not a soup'),
  ('dish_not', 'general', 'Це страва', 'Це просто набір продуктів', 'That''s a dish', 'That''s just ingredients'),
  ('tea_coffee', 'general', 'Чай', 'Кава', 'Tea', 'Coffee'),
  ('cook_order', 'general', 'Готувати вдома', 'Замовити доставку', 'Cook at home', 'Order in'),
  ('underrated_food', 'general', 'Недооцінена страва', 'Переоцінена страва', 'Underrated food', 'Overrated food'),
  ('city_village', 'general', 'Місто', 'Село', 'City', 'Countryside'),
  ('morning_night', 'general', 'Ранкова людина', 'Нічна людина', 'Morning person', 'Night owl'),
  ('summer_winter', 'general', 'Літо', 'Зима', 'Summer', 'Winter'),
  ('beach_mountains', 'general', 'Пляж', 'Гори', 'Beach', 'Mountains'),
  ('cat_dog', 'general', 'Кіт', 'Пес', 'Cat', 'Dog'),
  ('car_transit', 'general', 'Своє авто', 'Громадський транспорт', 'Own car', 'Public transport'),
  ('plan_improvise', 'general', 'Планувати', 'Імпровізувати', 'Plan it', 'Improvise'),
  ('save_spend', 'general', 'Відкладати', 'Витрачати', 'Save it', 'Spend it'),
  ('rent_buy', 'general', 'Орендувати', 'Купувати', 'Rent', 'Buy'),
  ('minimal_maximal', 'general', 'Мінімалізм', 'Максималізм', 'Minimalism', 'Maximalism'),
  ('early_late', 'general', 'Приходити раніше', 'Спізнюватися', 'Show up early', 'Show up late'),
  ('text_call', 'general', 'Написати', 'Подзвонити', 'Text', 'Call'),
  ('email_meeting', 'general', 'Лист', 'Зустріч', 'An email', 'A meeting'),
  ('remote_office', 'general', 'Віддалено', 'В офісі', 'Remote', 'In the office'),
  ('weekday_weekend', 'general', 'Будні', 'Вихідні', 'Weekday', 'Weekend'),
  ('shower_am_pm', 'general', 'Душ зранку', 'Душ ввечері', 'Morning shower', 'Evening shower'),
  ('socks_barefoot', 'general', 'Шкарпетки вдома', 'Босоніж', 'Socks indoors', 'Barefoot'),
  ('window_aisle', 'general', 'Місце біля вікна', 'Біля проходу', 'Window seat', 'Aisle seat'),
  ('carryon_suitcase', 'general', 'Тільки ручна поклажа', 'Велика валіза', 'Carry-on only', 'Big suitcase'),
  ('map_wander', 'general', 'За маршрутом', 'Куди очі дивляться', 'Follow the map', 'Just wander'),
  ('socks_sandals', 'general', 'Це нормально', 'Це злочин проти моди', 'Perfectly fine', 'A fashion crime'),
  ('hoard_declutter', 'general', 'Зберігати все', 'Викидати', 'Keep everything', 'Throw it out'),
  ('list_memory', 'general', 'Записати в список', 'Тримати в голові', 'Make a list', 'Keep it in your head'),
  ('handwrite_type', 'general', 'Від руки', 'Друкувати', 'Handwrite', 'Type'),
  ('paper_digital', 'general', 'Папір', 'Цифра', 'Paper', 'Digital'),
  ('book_movie', 'general', 'Книга', 'Фільм', 'The book', 'The movie'),
  ('cinema_home', 'general', 'Кінотеатр', 'Дома на дивані', 'Cinema', 'Home couch'),
  ('binge_weekly', 'general', 'Залпом', 'По серії на тиждень', 'Binge it', 'One episode a week'),
  ('spoilers_ok_no', 'general', 'Спойлери — це ок', 'Спойлери — злочин', 'Spoilers are fine', 'Spoilers are a crime'),
  ('classic_trend', 'general', 'Класика', 'Тренд', 'A classic', 'A trend'),
  ('timeless_dated', 'general', 'Не старіє', 'Застаріло', 'Timeless', 'Dated'),
  ('art_not_art', 'general', 'Це мистецтво', 'Це не мистецтво', 'This is art', 'This is not art'),
  ('mainstream_indie', 'general', 'Мейнстрим', 'Інді', 'Mainstream', 'Indie'),
  ('viral_niche', 'general', 'Вірусне', 'Нішеве', 'Viral', 'Niche'),
  ('meme_alive_dead', 'general', 'Живий мем', 'Мертвий мем', 'Living meme', 'Dead meme'),
  ('nostalgic_futuristic', 'general', 'Ностальгічно', 'Футуристично', 'Nostalgic', 'Futuristic'),
  ('retro_modern', 'general', 'Ретро', 'Сучасне', 'Retro', 'Modern'),
  ('analog_digital', 'general', 'Аналогове', 'Цифрове', 'Analogue', 'Digital'),
  ('handmade_massprod', 'general', 'Ручна робота', 'Масове виробництво', 'Handmade', 'Mass produced'),
  ('ad_content', 'general', 'Реклама', 'Контент', 'An ad', 'Content'),
  ('news_gossip', 'general', 'Новина', 'Плітка', 'News', 'Gossip'),
  ('myth_fact', 'general', 'Міф', 'Факт', 'Myth', 'Fact'),
  ('conspiracy_plausible', 'general', 'Теорія змови', 'Схоже на правду', 'Conspiracy theory', 'Plausible'),
  ('superstition_science', 'general', 'Забобон', 'Наука', 'Superstition', 'Science'),
  ('guilty_proud', 'general', 'Соромно, але люблю', 'Гордо люблю', 'Guilty pleasure', 'Proud favourite'),
  ('talent_luck', 'general', 'Талант', 'Щастя', 'Talent', 'Luck'),
  ('skill_chance_game', 'general', 'Гра на вміння', 'Гра на удачу', 'Game of skill', 'Game of luck'),
  ('sport_not_sport', 'general', 'Це спорт', 'Це не спорт', 'That''s a sport', 'That''s not a sport'),
  ('toy_collectible', 'general', 'Іграшка', 'Колекційна річ', 'A toy', 'A collectible'),
  ('tool_weapon', 'general', 'Інструмент', 'Зброя', 'A tool', 'A weapon'),
  ('pet_wild', 'general', 'Домашня тварина', 'Дика тварина', 'A pet', 'A wild animal'),
  ('friend_acquaintance', 'general', 'Друг', 'Знайомий', 'A friend', 'An acquaintance'),
  ('hobby_job', 'general', 'Хобі', 'Робота', 'A hobby', 'A job'),
  ('work_play', 'general', 'Робота', 'Розвага', 'Work', 'Play'),
  ('compliment_insult', 'general', 'Комплімент', 'Образа', 'A compliment', 'An insult'),
  ('flirting_friendly', 'general', 'Флірт', 'Просто дружньо', 'Flirting', 'Just being friendly'),
  ('confident_arrogant', 'general', 'Впевнено', 'Зарозуміло', 'Confident', 'Arrogant'),
  ('honest_harsh', 'general', 'Відкрито', 'Жорстко', 'Honest', 'Harsh'),
  ('brave_reckless', 'general', 'Смілива ідея', 'Безрозсудна ідея', 'Brave idea', 'Reckless idea'),
  ('kind_naive', 'general', 'Добрий', 'Наївний', 'Kind', 'Naive'),
  ('clever_smartass', 'general', 'Розумно', 'Вискочка', 'Clever', 'Smart-ass'),
  ('leader_boss', 'general', 'Лідер', 'Начальник', 'A leader', 'A boss'),
  ('rule_suggestion', 'general', 'Правило', 'Порада', 'A rule', 'A suggestion'),
  ('tradition_habit', 'general', 'Традиція', 'Просто звичка', 'Tradition', 'Just a habit'),
  ('legal_illegal', 'general', 'Законно', 'Незаконно', 'Legal', 'Illegal'),
  ('ethical_shady', 'general', 'Етично', 'Сумнівно', 'Ethical', 'Shady'),
  ('forgivable_not', 'general', 'Можна пробачити', 'Не можна пробачити', 'Forgivable', 'Unforgivable'),
  ('crime_prank', 'general', 'Злочин', 'Жарт', 'A crime', 'A prank'),
  ('petty_serious', 'general', 'Дрібниця', 'Серйозна справа', 'Petty', 'Serious business'),
  ('red_green_flag', 'general', 'Red flag', 'Green flag', 'Red flag', 'Green flag'),
  ('dealbreaker_quirk', 'general', 'Ділбрейкер', 'Просто дивинка', 'Dealbreaker', 'Just a quirk'),
  ('mature_childish', 'general', 'Доросло', 'По-дитячому', 'Mature', 'Childish'),
  ('for_adults_kids', 'general', 'Для дорослих', 'Для дітей', 'For adults', 'For kids'),
  ('worth_it_ripoff', 'general', 'Варте грошей', 'Здирництво', 'Worth the money', 'A rip-off'),
  ('investment_waste', 'general', 'Інвестиція', 'Витрата', 'An investment', 'A waste'),
  ('need_want', 'general', 'Потрібно', 'Хочеться', 'A need', 'A want'),
  ('essential_optional', 'general', 'Обов''язкове', 'Необов''язкове', 'Essential', 'Optional'),
  ('luxury_basic', 'general', 'Люкс', 'База', 'Luxury', 'Basic'),
  ('easy_learn_hard_master', 'general', 'Легко навчитися', 'Важко опанувати', 'Easy to learn', 'Hard to master'),
  ('beginner_expert', 'general', 'Для новачка', 'Для експерта', 'Beginner', 'Expert'),
  ('overqualified_under', 'general', 'Надкваліфікований', 'Недокваліфікований', 'Overqualified', 'Underqualified'),
  ('natural_practised', 'general', 'Від природи', 'Натреновано', 'Natural talent', 'Practised'),
  ('team_solo', 'general', 'Командна гра', 'Соло', 'Team game', 'Solo'),
  ('cooperate_compete', 'general', 'Співпраця', 'Конкуренція', 'Cooperate', 'Compete'),
  ('winning_fun', 'general', 'Головне перемога', 'Головне весело', 'Winning matters', 'Fun matters'),
  ('process_result', 'general', 'Процес', 'Результат', 'The process', 'The result'),
  ('quality_speed', 'general', 'Якість', 'Швидкість', 'Quality', 'Speed'),
  ('perfect_done', 'general', 'Ідеально', 'Просто зроблено', 'Perfect', 'Just done'),
  ('details_bigpicture', 'general', 'Деталі', 'Загальна картина', 'The details', 'The big picture'),
  ('rules_vibes', 'general', 'За правилами', 'На відчуттях', 'By the rules', 'By vibes'),
  ('logic_emotion', 'general', 'Логіка', 'Емоції', 'Logic', 'Emotion'),
  ('head_heart', 'general', 'Голова', 'Серце', 'Head', 'Heart'),
  ('optimist_pessimist', 'general', 'Оптиміст', 'Песиміст', 'Optimist', 'Pessimist'),
  ('realist_dreamer', 'general', 'Реаліст', 'Мрійник', 'Realist', 'Dreamer'),
  ('patient_impatient', 'general', 'Терплячий', 'Нетерплячий', 'Patient', 'Impatient'),
  ('stubborn_flexible', 'general', 'Впертий', 'Гнучкий', 'Stubborn', 'Flexible'),
  ('loyal_fickle', 'general', 'Вірний', 'Непостійний', 'Loyal', 'Fickle'),
  ('generous_stingy', 'general', 'Щедрий', 'Скупий', 'Generous', 'Stingy'),
  ('humble_showoff', 'general', 'Скромний', 'Хвалько', 'Humble', 'Show-off'),
  ('lazy_workaholic', 'general', 'Лінивий', 'Трудоголік', 'Lazy', 'Workaholic'),
  ('spontaneous_scheduled', 'general', 'Спонтанно', 'За розписом', 'Spontaneous', 'Scheduled'),
  ('risktaker_cautious', 'general', 'Ризикун', 'Обережний', 'Risk-taker', 'Cautious'),
  ('leads_follows', 'general', 'Веде за собою', 'Йде за іншими', 'Leads', 'Follows'),
  ('talker_listener', 'general', 'Говорить', 'Слухає', 'Talker', 'Listener'),
  ('party_home', 'general', 'Вечірка', 'Вечір дома', 'Party', 'Night in'),
  ('smalltalk_deep', 'general', 'Смолток', 'Глибокі теми', 'Small talk', 'Deep talk'),
  ('dance_wallflower', 'general', 'Танцювати', 'Стояти біля стіни', 'Dance', 'Hold up the wall'),
  ('music_loud_silence', 'general', 'Музика на повну', 'Повна тиша', 'Music blasting', 'Total silence'),
  ('early_late_adopter', 'general', 'Ранній адоптер', 'Переходить останнім', 'Early adopter', 'Late adopter'),
  ('gadget_lover_sceptic', 'general', 'Любить гаджети', 'Не довіряє технологіям', 'Gadget lover', 'Tech sceptic'),
  ('android_ios', 'general', 'Android', 'iOS', 'Android', 'iOS'),
  ('pc_console', 'general', 'ПК', 'Консоль', 'PC', 'Console'),
  ('mac_windows', 'general', 'Mac', 'Windows', 'Mac', 'Windows'),
  ('light_dark_mode', 'general', 'Світла тема', 'Темна тема', 'Light mode', 'Dark mode'),
  ('tabs_spaces', 'general', 'Табуляція', 'Пробіли', 'Tabs', 'Spaces'),
  ('emoji_plaintext', 'general', 'Емодзі', 'Сухий текст', 'Emoji', 'Plain text'),
  ('voice_text', 'general', 'Голосове', 'Текстом', 'Voice note', 'Text message'),
  ('camera_on_off', 'general', 'Камера ввімкнена', 'Камера вимкнена', 'Camera on', 'Camera off'),
  ('notifications_all_muted', 'general', 'Усі нотифікації', 'Усе вимкнено', 'All notifications on', 'Everything muted'),
  ('inbox_zero_thousand', 'general', 'Inbox zero', 'Тисяча непрочитаних', 'Inbox zero', 'A thousand unread'),
  ('one_tab_hundred', 'general', 'Одна вкладка', 'Сто вкладок', 'One tab', 'A hundred tabs'),
  ('bookmark_research', 'general', 'Зберегти в закладки', 'Шукати заново', 'Bookmark it', 'Search again'),
  ('reads_terms_never', 'general', 'Читає умови', 'Ніколи не читає', 'Reads the terms', 'Never reads them'),
  ('passwordmanager_notebook', 'general', 'Менеджер паролів', 'Записник на столі', 'Password manager', 'A notebook'),
  ('backup_yolo', 'general', 'Робить бекапи', 'YOLO', 'Makes backups', 'YOLO'),
  ('update_now_later', 'general', 'Оновити зараз', 'Нагадати пізніше', 'Update now', 'Remind me later'),
  ('significant_noise', 'analytics', 'Статистично значуще', 'Просто шум', 'Statistically significant', 'Just noise'),
  ('signal_noise', 'analytics', 'Сигнал', 'Шум', 'Signal', 'Noise'),
  ('corr_causation', 'analytics', 'Кореляція', 'Причинність', 'Correlation', 'Causation'),
  ('p005_p05', 'analytics', 'p < 0.05', 'p = 0.5', 'p < 0.05', 'p = 0.5'),
  ('mean_median', 'analytics', 'Середнє', 'Медіана', 'Mean', 'Median'),
  ('sample_population', 'analytics', 'Вибірка', 'Уся сукупність', 'Sample', 'Population'),
  ('outlier_typical', 'analytics', 'Викид', 'Типове значення', 'Outlier', 'Typical value'),
  ('underpowered_powered', 'analytics', 'Замала потужність', 'Достатня потужність', 'Underpowered', 'Well-powered'),
  ('statsig_practical', 'analytics', 'Статистично значуще', 'Практично значуще', 'Statistically significant', 'Practically significant'),
  ('bias_variance', 'analytics', 'Зсув', 'Розсіювання', 'Bias', 'Variance'),
  ('simpson_straight', 'analytics', 'Парадокс Сімпсона', 'Усе прямолінійно', 'Simpson''s paradox', 'Straightforward'),
  ('survivorship_full', 'analytics', 'Помилка виживання', 'Повна картина', 'Survivorship bias', 'Full picture'),
  ('selection_random', 'analytics', 'Зсув відбору', 'Випадкова вибірка', 'Selection bias', 'Random sample'),
  ('hypothesis_fishing', 'analytics', 'Гіпотеза', 'Рибалка по даних', 'A hypothesis', 'Fishing for results'),
  ('phacking_honest', 'analytics', 'p-hacking', 'Чесний аналіз', 'p-hacking', 'Honest analysis'),
  ('ab_test_obvious', 'analytics', 'Варто A/B-тестити', 'І так очевидно', 'Worth A/B testing', 'Obvious already'),
  ('experiment_rollout', 'analytics', 'Експеримент', 'Повний ролаут', 'An experiment', 'A full rollout'),
  ('holdout_everyone', 'analytics', 'Холдаут-група', 'Усі юзери', 'Holdout group', 'Everyone'),
  ('srm_balanced', 'analytics', 'Перекіс у групах', 'Групи збалансовані', 'Sample ratio mismatch', 'Balanced groups'),
  ('peeking_waiting', 'analytics', 'Підглядати в тест', 'Дочекатися кінця', 'Peeking', 'Waiting it out'),
  ('tiny_huge_effect', 'analytics', 'Мікроскопічний ефект', 'Величезний ефект', 'Tiny effect', 'Huge effect'),
  ('ship_iterate', 'analytics', 'Запускати', 'Ще покрутити', 'Ship it', 'Keep tuning'),
  ('short_long_term', 'analytics', 'Короткий термін', 'Довгий термін', 'Short term', 'Long term'),
  ('clean_dirty_data', 'analytics', 'Чисті дані', 'Брудні дані', 'Clean data', 'Dirty data'),
  ('more_enough_data', 'analytics', 'Треба ще даних', 'Даних достатньо', 'Need more data', 'Enough data'),
  ('bug_or_behaviour', 'analytics', 'Це баг у трекінгу', 'Це реальна поведінка', 'Tracking bug', 'Real user behaviour'),
  ('tracking_broken_fine', 'analytics', 'Трекінг зламався', 'Трекінг у нормі', 'Tracking is broken', 'Tracking is fine'),
  ('event_missing_ok', 'analytics', 'Івент не надсилається', 'Усе логується', 'Event is missing', 'Everything logs'),
  ('schema_drift_stable', 'analytics', 'Схема поплила', 'Схема стабільна', 'Schema drift', 'Stable schema'),
  ('etl_late_ontime', 'analytics', 'Пайплайн запізнився', 'Прийшло вчасно', 'Pipeline is late', 'On time'),
  ('backfill_forward', 'analytics', 'Перезалити історію', 'Тільки з цього дня', 'Backfill history', 'Only going forward'),
  ('batch_streaming', 'analytics', 'Батч', 'Стрімінг', 'Batch', 'Streaming'),
  ('warehouse_lake', 'analytics', 'Сховище', 'Дата-лейк', 'Warehouse', 'Data lake'),
  ('realtime_quarter', 'analytics', 'Реал-тайм', 'Раз на квартал', 'Real-time', 'Once a quarter'),
  ('automate_manual', 'analytics', 'Автоматизувати', 'Зробити руками', 'Automate', 'Do it manually'),
  ('dashboard_export', 'analytics', 'Дашборд', 'Ручний експорт', 'Dashboard', 'Manual export'),
  ('sql_spreadsheet', 'analytics', 'SQL', 'Табличка в екселі', 'SQL', 'A spreadsheet'),
  ('notebook_production', 'analytics', 'Ноутбук на коліні', 'Прод', 'A notebook', 'Production'),
  ('prototype_pipeline', 'analytics', 'Прототип', 'Продакшн-пайплайн', 'Prototype', 'Production pipeline'),
  ('model_heuristic', 'analytics', 'Модель', 'Проста евристика', 'A model', 'A simple heuristic'),
  ('ml_ifelse', 'analytics', 'ML', 'Кілька if-ів', 'ML', 'A few if-statements'),
  ('explainable_blackbox', 'analytics', 'Інтерпретовно', 'Чорна скринька', 'Explainable', 'Black box'),
  ('overfit_underfit', 'analytics', 'Перенавчання', 'Недонавчання', 'Overfitting', 'Underfitting'),
  ('precision_recall', 'analytics', 'Precision', 'Recall', 'Precision', 'Recall'),
  ('false_pos_neg', 'analytics', 'Хибнопозитивний', 'Хибнонегативний', 'False positive', 'False negative'),
  ('train_prod_gap', 'analytics', 'Розрив train/prod', 'Усе співпадає', 'Train/prod gap', 'Consistent'),
  ('feature_leak_clean', 'analytics', 'Лік фіч', 'Чисті фічі', 'Feature leakage', 'Clean features'),
  ('label_noise_clean', 'analytics', 'Шумні мітки', 'Чисті мітки', 'Noisy labels', 'Clean labels'),
  ('baseline_sota', 'analytics', 'Бейзлайн', 'SOTA', 'Baseline', 'State of the art'),
  ('goodenough_perfect', 'analytics', 'Достатньо добре', 'Ідеальна точність', 'Good enough', 'Perfect accuracy'),
  ('real_vanity', 'analytics', 'Справжня метрика', 'Vanity-метрика', 'Real metric', 'Vanity metric'),
  ('northstar_random', 'analytics', 'North star', 'Випадкова метрика', 'North star metric', 'Random metric'),
  ('leading_lagging', 'analytics', 'Опереджальний індикатор', 'Запізнілий індикатор', 'Leading indicator', 'Lagging indicator'),
  ('one_metric_twenty', 'analytics', 'Одна метрика', 'Двадцять метрик', 'One metric', 'Twenty metrics'),
  ('absolute_relative', 'analytics', 'Абсолютні числа', 'Відсотки', 'Absolute numbers', 'Percentages'),
  ('cohort_snapshot', 'analytics', 'Когортний аналіз', 'Знімок на дату', 'Cohort analysis', 'Point-in-time snapshot'),
  ('seasonality_trend', 'analytics', 'Сезонність', 'Тренд', 'Seasonality', 'Trend'),
  ('spike_drift', 'analytics', 'Різкий стрибок', 'Плавний дрейф', 'A spike', 'A slow drift'),
  ('funnel_leak_ok', 'analytics', 'Витік у воронці', 'Здорова воронка', 'Funnel leak', 'Healthy funnel'),
  ('dau_mau', 'analytics', 'DAU', 'MAU', 'DAU', 'MAU'),
  ('retention_acquisition', 'analytics', 'Ретеншн', 'Залучення', 'Retention', 'Acquisition'),
  ('churn_growth', 'analytics', 'Відтік', 'Ріст', 'Churn', 'Growth'),
  ('ltv_cac', 'analytics', 'LTV', 'CAC', 'LTV', 'CAC'),
  ('revenue_engagement', 'analytics', 'Дохід', 'Залученість', 'Revenue', 'Engagement'),
  ('segment_average', 'analytics', 'По сегментах', 'У середньому', 'By segment', 'On average'),
  ('definition_agreed_disputed', 'analytics', 'Метрика узгоджена', 'Кожен рахує по-своєму', 'Agreed definition', 'Everyone counts differently'),
  ('datadriven_gut', 'analytics', 'Data-driven', 'На відчуттях', 'Data-driven', 'Gut feeling'),
  ('qual_quant', 'analytics', 'Якісні дані', 'Кількісні дані', 'Qualitative', 'Quantitative'),
  ('survey_logs', 'analytics', 'Опитування', 'Логи', 'A survey', 'The logs'),
  ('interview_dashboard', 'analytics', 'Інтерв''ю з юзером', 'Дашборд', 'A user interview', 'A dashboard'),
  ('selfreported_measured', 'analytics', 'Зі слів юзерів', 'Заміряно', 'Self-reported', 'Measured'),
  ('chartjunk_clear', 'analytics', 'Перевантажений графік', 'Ясний графік', 'Chart junk', 'A clear chart'),
  ('pie_bar', 'analytics', 'Пайчарт', 'Барчарт', 'Pie chart', 'Bar chart'),
  ('log_linear', 'analytics', 'Логарифмічна шкала', 'Лінійна шкала', 'Log scale', 'Linear scale'),
  ('axis_zero_cropped', 'analytics', 'Вісь від нуля', 'Обрізана вісь', 'Axis from zero', 'Cropped axis'),
  ('table_chart', 'analytics', 'Таблиця', 'Графік', 'A table', 'A chart'),
  ('onepager_deck', 'analytics', 'Одна сторінка', 'Дека на сорок слайдів', 'A one-pager', 'A 40-slide deck'),
  ('adhoc_recurring', 'analytics', 'Ad-hoc запит', 'Регулярний звіт', 'Ad-hoc request', 'Recurring report'),
  ('selfserve_ask_analyst', 'analytics', 'Self-serve', 'Питати аналітика', 'Self-serve', 'Ask the analyst'),
  ('documented_tribal', 'analytics', 'Задокументовано', 'Знання в головах', 'Documented', 'Tribal knowledge'),
  ('pii_anonymous', 'analytics', 'Персональні дані', 'Анонімно', 'Personal data', 'Anonymous'),
  ('gdpr_risk_safe', 'analytics', 'Ризик для GDPR', 'Безпечно з даними', 'GDPR risk', 'Privacy-safe')
on conflict (key) do update set
  category  = excluded.category,
  left_ua   = excluded.left_ua,
  right_ua  = excluded.right_ua,
  left_en   = excluded.left_en,
  right_en  = excluded.right_en;

-- Sanity check: how many playable pairs per category.
select category, count(*) filter (where enabled) as enabled, count(*) as total
from public.scales
group by category
order by category;
